### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by tsanchez0** [rhelmer/caching-s3-proxy#5]
Hi, 
I'm using caching-s3-proxy the last two weeks to image proxy for my website. it works fine until the size (or the number of cached elements) grows to more than 1 GB, the CPU usage elevates to 100% and serves request too slowly.
I tried running as a single service or with workers but I got the same result.

Does anyone else have this problem?

Thank you very much for your work!

**Comment by rhelmer** [comment]
Hi! Thanks for reporting this @tsanchez0.

It looks like I didn't document this, but you probably need to bump the capacity, which is 1GB by default (as you can see in https://github.com/rhelmer/caching-s3-proxy/blob/master/proxy/run.py#L9).

The `run.py` honors a `CAPACITY` environment variable, can you try setting this to something larger? Thanks!

**Comment by rhelmer** [comment]
I've added examples in https://github.com/rhelmer/caching-s3-proxy#running-standalone - if this doesn't work for you, or you have a better approach for handling this, please re-open!
